### ISSUE TITLE
Generate secure superuser passwords by default

### ISSUE THREAD

**Issue by gsiv** [OpenSlides/openslides-manage-service#86]
Currently, the `superuser` secret added by `openslides setup` appears to be hard-coded to `superuser`.

Furthermore, manually changing the password is not easy because, apparently, the file must not contain newline/linefeed.  This makes setting a secure password rather challenging for users, especially when the resulting error is this unclear:

```
$ openslides initial-data
Error: setting initial data: setting initial data: rpc error: code = Unknown desc = setting superadmin password: setting superadmin password: hashing passwort: auth service returned 400 Bad Request: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>SyntaxError: Unexpected token <br> in JSON at position 22<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at parse (/app/node_modules/body-parser/lib/types/json.js:89:19)<br> &nbsp; &nbsp;at /app/node_modules/body-parser/lib/read.js:121:18<br> &nbsp; &nbsp;at invokeCallback (/app/node_modules/raw-body/index.js:224:16)<br> &nbsp; &nbsp;at done (/app/node_modules/raw-body/index.js:213:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:273:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (node:events:402:35)<br> &nbsp; &nbsp;at endReadableNT (node:internal/streams/readable:1343:12)<br> &nbsp; &nbsp;at processTicksAndRejections (node:internal/process/task_queues:83:21)</pre>
</body>
</html>
```

The setup command should generate secure passwords by default.  Additionally, it may benefit from an option to set user-provided passwords.

**Comment by normanjaeckel** [comment]
Should be done.
